name: web_socket_channel
version: 2.5.0

description: >-
  StreamChannel wrappers for WebSockets. Provides a cross-platform
  WebSocketChannel API, a cross-platform implementation of that API that
  communicates over an underlying StreamChannel.
repository: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  async: ^2.13.0
  crypto: ^3.0.3
  stream_channel: ^2.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15